# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Binaries 

on:
  push:
    branches: [ "main", "7-inject-version-number-with-workflow" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_apk:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.0
      # - name: Get date variable
      #  run : $NOW=& Get-Date -format yyyy-MM-dd
      #    echo "NOW=$NOW" >> $env:GITHUB_ENV
      - run: flutter pub get
      # - run: flutter test
      - run: flutter build apk --build-number 1
      # - name: Build linux version
      #  run: flutter build linux --release
      - run: flutter build appbundle --build-number 1

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: build/app/outputs/flutter-apk/app-release.apk

  build_windows:
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter build windows --build-number 1
      - name: Upload Windows version
        uses: actions/upload-artifact@v4
        with:
          name: Windows version
          path: build/windows/x64/runner/Release
          
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter pub get
      - run: flutter build linux --release --build-number 1
      - name: Upload Linux version
        uses: actions/upload-artifact@v4
        with:
          name: Linux version
          path: build/linux/x64/release/bundle